ENVIRONMENT:
  MAX_EPISODE_STEPS: 2500
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  ACTION_SPACE_CONFIG: "v0"
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.1
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False
  SEMANTIC_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 256
    HEIGHT: 256
    HFOV: 79
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: MultiObjectNav-v1
  OBJECTS_PATH: "data/objects"
  INCLUDE_DISTRACTORS: True

  
  POSSIBLE_ACTIONS: ["FOUND", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT"]

  SUCCESS_DISTANCE: 1.0

  SENSORS: ['MULTI_OBJECT_GOAL_SENSOR', 'COMPASS_SENSOR', 'GPS_SENSOR']

  GOAL_SENSOR_UUID: multiobjectgoal

  MEASUREMENTS: [
    'EPISODE_LENGTH',
    'DISTANCE_TO_CURR_GOAL', 
    #'DISTANCE_TO_MULTI_GOAL',
    'SUB_SUCCESS', 
    'SUCCESS', 
    'MSPL', 
    'PERCENTAGE_SUCCESS', 
    'PSPL'
    ]

  SUCCESS:
    SUCCESS_DISTANCE: 0.5
  SUB_SUCCESS:
    SUCCESS_DISTANCE: 0.5
  PERCENTAGE_SUCCESS:
    SUCCESS_DISTANCE: 0.5
  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS

DATASET:
  TYPE: MultiObjectNav-v1
  SPLIT: minival
  SCENES_DIR: "data/scene_datasets/fphab/scenes"
  DATA_PATH: "data/datasets/{split}/{split}.json.gz"
